export const mockMovieResponse = {
  Title: "Spider-Man: Far from Home",
  Year: "2019",
  Rated: "PG-13",
  Released: "02 Jul 2019",
  Runtime: "129 min",
  Genre: "Action, Adventure, Comedy",
  Director: "Jon Watts",
  Writer: "Chris McKenna, Erik Sommers, Stan Lee",
  Actors: "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
  Plot: "Following the events of Avengers: Endgame (2019), Spider-Man must step up to take on new threats in a world that has changed forever.",
  Language: "English, Italian, Czech",
  Country: "United States, Czech Republic, Australia, Canada, Italy",
  Awards: "11 wins & 26 nominations",
  Poster:
    "https://m.media-amazon.com/images/M/MV5BODA5MTY0OWUtNjdlOC00NDI5LWE3NjYtNDM4MDI2MzE4OWUxXkEyXkFqcGdeQXVyOTAzODkzMjI@._V1_SX300.jpg",
  Ratings: [
    {
      Source: "Internet Movie Database",
      Value: "7.4/10",
    },
    {
      Source: "Rotten Tomatoes",
      Value: "91%",
    },
    {
      Source: "Metacritic",
      Value: "69/100",
    },
  ],
  Metascore: "69",
  imdbRating: "7.4",
  imdbVotes: "564,966",
  imdbID: "tt6320628",
  Type: "movie",
  DVD: "N/A",
  BoxOffice: "$391,283,774",
  Production: "N/A",
  Website: "N/A",
  Response: "True",
};
