on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: Run Automate Test on every Pull Request
jobs:
  build:
    name: Run Automate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 20.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.16.0
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run test
        run: npm test -- run --coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage
      - name: Build Project
        run: npm run build
      - name: Deploy to Vercel
        if: success()
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token=$VERCEL_TOKEN
